
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR CHARACTERS COLON COMMA DEF EQUAL EXPGRAM EXPRESSION HASHTAGS IGNORE INITVAR INITYACC LEFT LEFTBRACKET LEFTCOTTER LEXMARKER LITERALS NAMEFUNC NAMEPROD NAMEVAR PARSEYACC PRECEDENCE RE RETURNEDPRODS RIGHT RIGHTBRACKET RIGHTCOTTER SLEFTBRACKET SQM SRIGHTBRACKET STRING TOKENS UPPERWORD WORD YACCMARKERphrase : lex yacclex : LEXMARKER literals ignore tokens functionsliterals : LITERALS EQUAL CHARACTERS commentliterals : comment : HASHTAGS wordscomment : words : words WORDwords : WORDignore : IGNORE EQUAL CHARACTERS commentignore : tokens : TOKENS EQUAL SLEFTBRACKET tokenNames SRIGHTBRACKET commenttokens : tokenNames : tokenNames COMMA SQM UPPERWORD SQMtokenNames : SQM UPPERWORD SQMfunctions : functions functionfunctions : function : RE LEFTBRACKET content RIGHTBRACKET comment content : SQM UPPERWORD SQM COMMA EXPRESSIONcontent : SQM UPPERWORD SQM COMMA WORDcontent : STRING COMMA EXPRESSIONcontent : CHARACTERS COMMA EXPRESSIONyacc : YACCMARKER precedence comment precedence : PRECEDENCE EQUAL SLEFTBRACKET precedences SRIGHTBRACKETprecedence : precedences : precedences tokenprecedenceprecedences : tokenprecedence : LEFTBRACKET rl COMMA nametokensprec RIGHTBRACKET COMMAtokenprecedence : rl : SQM RIGHT SQMrl : SQM LEFT SQMnametokensprec :  nametokensprec COMMA SQM UPPERWORD SQMnametokensprec : nametokensprec COMMA SQM CHAR SQMnametokensprec : SQM CHAR SQMnametokensprec : SQM UPPERWORD SQM'
    
_lr_action_items = {'LEXMARKER':([0,],[3,]),'$end':([1,4,5,8,13,20,21,27,33,],[0,-1,-24,-6,-22,-5,-8,-7,-23,]),'YACCMARKER':([2,3,6,10,16,19,20,21,23,25,26,27,29,32,45,51,55,62,],[5,-4,-10,-12,-16,-6,-5,-8,-2,-6,-3,-7,-15,-9,-6,-6,-11,-17,]),'LITERALS':([3,],[7,]),'IGNORE':([3,6,19,20,21,26,27,],[-4,11,-6,-5,-8,-3,-7,]),'TOKENS':([3,6,10,19,20,21,25,26,27,32,],[-4,-10,17,-6,-5,-8,-6,-3,-7,-9,]),'RE':([3,6,10,16,19,20,21,23,25,26,27,29,32,45,51,55,62,],[-4,-10,-12,-16,-6,-5,-8,30,-6,-3,-7,-15,-9,-6,-6,-11,-17,]),'PRECEDENCE':([5,],[9,]),'HASHTAGS':([5,8,19,25,33,45,51,],[-24,14,14,14,-23,14,14,]),'EQUAL':([7,9,11,17,],[12,15,18,24,]),'CHARACTERS':([12,18,36,],[19,25,44,]),'WORD':([14,20,21,27,71,],[21,27,-8,-7,78,]),'SLEFTBRACKET':([15,24,],[22,31,]),'SRIGHTBRACKET':([22,28,34,37,57,72,74,],[-26,33,-25,45,-14,-13,-27,]),'LEFTBRACKET':([22,28,30,34,74,],[-26,35,36,-25,-27,]),'SQM':([31,35,36,46,47,48,49,50,52,66,67,69,70,79,80,],[38,40,42,56,57,59,60,61,63,72,73,75,76,81,82,]),'STRING':([36,],[43,]),'COMMA':([37,39,43,44,57,58,60,61,63,68,72,75,76,81,82,],[46,48,53,54,-14,67,-29,-30,71,74,-13,-33,-34,-31,-32,]),'UPPERWORD':([38,42,56,59,73,],[47,52,66,70,79,]),'RIGHT':([40,],[49,]),'LEFT':([40,],[50,]),'RIGHTBRACKET':([41,58,64,65,75,76,77,78,81,82,],[51,68,-20,-21,-33,-34,-18,-19,-31,-32,]),'EXPRESSION':([53,54,71,],[64,65,77,]),'CHAR':([59,73,],[69,80,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'phrase':([0,],[1,]),'lex':([0,],[2,]),'yacc':([2,],[4,]),'literals':([3,],[6,]),'precedence':([5,],[8,]),'ignore':([6,],[10,]),'comment':([8,19,25,45,51,],[13,26,32,55,62,]),'tokens':([10,],[16,]),'words':([14,],[20,]),'functions':([16,],[23,]),'precedences':([22,],[28,]),'function':([23,],[29,]),'tokenprecedence':([28,],[34,]),'tokenNames':([31,],[37,]),'rl':([35,],[39,]),'content':([36,],[41,]),'nametokensprec':([48,],[58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> phrase","S'",1,None,None,None),
  ('phrase -> lex yacc','phrase',2,'p_phrase','parser_yacc.py',8),
  ('lex -> LEXMARKER literals ignore tokens functions','lex',5,'p_lex','parser_yacc.py',11),
  ('literals -> LITERALS EQUAL CHARACTERS comment','literals',4,'p_literals','parser_yacc.py',104),
  ('literals -> <empty>','literals',0,'p_literals_empty','parser_yacc.py',108),
  ('comment -> HASHTAGS words','comment',2,'p_comment','parser_yacc.py',112),
  ('comment -> <empty>','comment',0,'p_comment_empty','parser_yacc.py',117),
  ('words -> words WORD','words',2,'p_words','parser_yacc.py',121),
  ('words -> WORD','words',1,'p_words_stop','parser_yacc.py',125),
  ('ignore -> IGNORE EQUAL CHARACTERS comment','ignore',4,'p_ignore','parser_yacc.py',129),
  ('ignore -> <empty>','ignore',0,'p_ignore_empty','parser_yacc.py',133),
  ('tokens -> TOKENS EQUAL SLEFTBRACKET tokenNames SRIGHTBRACKET comment','tokens',6,'p_tokens','parser_yacc.py',136),
  ('tokens -> <empty>','tokens',0,'p_tokens_empty','parser_yacc.py',140),
  ('tokenNames -> tokenNames COMMA SQM UPPERWORD SQM','tokenNames',5,'p_tokenNames','parser_yacc.py',143),
  ('tokenNames -> SQM UPPERWORD SQM','tokenNames',3,'p_tokenNames_stop','parser_yacc.py',147),
  ('functions -> functions function','functions',2,'p_functions','parser_yacc.py',151),
  ('functions -> <empty>','functions',0,'p_functions_empty','parser_yacc.py',155),
  ('function -> RE LEFTBRACKET content RIGHTBRACKET comment','function',5,'p_function','parser_yacc.py',159),
  ('content -> SQM UPPERWORD SQM COMMA EXPRESSION','content',5,'p_content_returned','parser_yacc.py',164),
  ('content -> SQM UPPERWORD SQM COMMA WORD','content',5,'p_content_returnedWord','parser_yacc.py',168),
  ('content -> STRING COMMA EXPRESSION','content',3,'p_content_string','parser_yacc.py',172),
  ('content -> CHARACTERS COMMA EXPRESSION','content',3,'p_content_characters','parser_yacc.py',177),
  ('yacc -> YACCMARKER precedence comment','yacc',3,'p_yacc','parser_yacc.py',188),
  ('precedence -> PRECEDENCE EQUAL SLEFTBRACKET precedences SRIGHTBRACKET','precedence',5,'p_precedence','parser_yacc.py',192),
  ('precedence -> <empty>','precedence',0,'p_precedence_empty','parser_yacc.py',196),
  ('precedences -> precedences tokenprecedence','precedences',2,'p_precedences_varios','parser_yacc.py',201),
  ('precedences -> <empty>','precedences',0,'p_precedences_vazio','parser_yacc.py',204),
  ('tokenprecedence -> LEFTBRACKET rl COMMA nametokensprec RIGHTBRACKET COMMA','tokenprecedence',6,'p_tokenprecedence','parser_yacc.py',207),
  ('tokenprecedence -> <empty>','tokenprecedence',0,'p_tokenprecedence_vazio','parser_yacc.py',212),
  ('rl -> SQM RIGHT SQM','rl',3,'p_rl_r','parser_yacc.py',217),
  ('rl -> SQM LEFT SQM','rl',3,'p_rl_l','parser_yacc.py',220),
  ('nametokensprec -> nametokensprec COMMA SQM UPPERWORD SQM','nametokensprec',5,'p_nametokensprec','parser_yacc.py',224),
  ('nametokensprec -> nametokensprec COMMA SQM CHAR SQM','nametokensprec',5,'p_nametokensprec_char','parser_yacc.py',228),
  ('nametokensprec -> SQM CHAR SQM','nametokensprec',3,'p_nametokensprec_char_single','parser_yacc.py',232),
  ('nametokensprec -> SQM UPPERWORD SQM','nametokensprec',3,'p_nametokensprec_upperword_single','parser_yacc.py',237),
]
