
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DELIM_ABRIR DELIM_FECHAR NUM PAL SEPARATORLista : DELIM_ABRIR Lista2Lista2 : LCont DELIM_FECHARLista2 : DELIM_FECHARLCont : NUM LCont2LCont : PAL LCont2LCont2 : SEPARATOR NUM LCont2LCont2 : SEPARATOR PAL LCont2LCont2 : '
    
_lr_action_items = {'DELIM_ABRIR':([0,],[2,]),'$end':([1,3,5,8,],[0,-1,-3,-2,]),'DELIM_FECHAR':([2,4,6,7,9,11,12,13,14,15,],[5,8,-8,-8,-4,-5,-8,-8,-6,-7,]),'NUM':([2,10,],[6,12,]),'PAL':([2,10,],[7,13,]),'SEPARATOR':([6,7,12,13,],[10,10,10,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,],[1,]),'Lista2':([2,],[3,]),'LCont':([2,],[4,]),'LCont2':([6,7,12,13,],[9,11,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> DELIM_ABRIR Lista2','Lista',2,'p_Lista','listas_yacc.py',10),
  ('Lista2 -> LCont DELIM_FECHAR','Lista2',2,'p_Lista2','listas_yacc.py',13),
  ('Lista2 -> DELIM_FECHAR','Lista2',1,'p_lista2_vazia','listas_yacc.py',16),
  ('LCont -> NUM LCont2','LCont',2,'p_LCont','listas_yacc.py',19),
  ('LCont -> PAL LCont2','LCont',2,'p_LCont_pal','listas_yacc.py',23),
  ('LCont2 -> SEPARATOR NUM LCont2','LCont2',3,'p_LCont2','listas_yacc.py',27),
  ('LCont2 -> SEPARATOR PAL LCont2','LCont2',3,'p_LCont2_pal','listas_yacc.py',31),
  ('LCont2 -> <empty>','LCont2',0,'p_LCont2_vazio','listas_yacc.py',35),
]
